pub mod api_surface;
pub mod architecture;
pub mod blast_radius;
pub mod call_graph;
pub mod co_change;
pub mod cross_lang;
pub mod data_flow;
pub mod dead_code;
pub mod drift;
pub mod health;
#[cfg(feature = "visual")]
pub mod onboarding;
pub mod pagerank;
pub mod predict;
pub mod recent_changes;
pub mod risk;
pub mod security;
pub mod test_map;
