use crate::budget::counter::TokenCounter;
use crate::cache;
use crate::cli::OutputFormat;
use crate::index::CodebaseIndex;
use crate::scanner::Scanner;
use std::io::Write;
use std::path::Path;

fn build_index(path: &Path) -> Result<CodebaseIndex, Box<dyn std::error::Error>> {
    let counter = TokenCounter::new();
    let scanner = Scanner::new(path)?;
    let files = scanner.scan_workspace(None)?;
    if files.is_empty() {
        return Err("no source files found".into());
    }
    let (parse_results, content_map) =
        cache::parse::parse_with_cache(&files, path, &counter, false);
    let index = CodebaseIndex::build_with_content(files, parse_results, &counter, content_map);
    Ok(index)
}

/// Renders basic onboarding guide content from the index.
///
/// Tasks 16-20 will replace this with the full OnboardingMap pipeline.
/// For now this produces a structured starter guide from index statistics.
fn render_onboarding(index: &CodebaseIndex, format: &OutputFormat) -> String {
    match format {
        OutputFormat::Json => render_onboarding_json(index),
        OutputFormat::Xml => render_onboarding_xml(index),
        OutputFormat::Markdown => render_onboarding_markdown(index),
    }
}

fn render_onboarding_markdown(index: &CodebaseIndex) -> String {
    let mut out = String::new();

    out.push_str("# Codebase Onboarding Guide\n\n");
    out.push_str("> Generated by cxpak. Full OnboardingMap available after Task 16-20.\n\n");

    out.push_str("## Overview\n\n");
    out.push_str(&format!("- **Files:** {}\n", index.total_files));
    out.push_str(&format!(
        "- **Estimated tokens:** ~{}k\n",
        index.total_tokens / 1000
    ));

    if !index.language_stats.is_empty() {
        out.push_str("- **Languages:**\n");
        let mut langs: Vec<_> = index.language_stats.iter().collect();
        langs.sort_by(|a, b| b.1.file_count.cmp(&a.1.file_count));
        for (lang, stats) in &langs {
            out.push_str(&format!("  - {} ({} files)\n", lang, stats.file_count));
        }
    }

    out.push_str("\n## Entry Points\n\n");
    let entry_points: Vec<_> = index
        .files
        .iter()
        .filter(|f| {
            let p = &f.relative_path;
            p == "src/main.rs"
                || p == "src/lib.rs"
                || p == "main.py"
                || p == "index.ts"
                || p == "index.js"
                || p.ends_with("/main.rs")
                || p.ends_with("/lib.rs")
        })
        .collect();

    if entry_points.is_empty() {
        out.push_str("No conventional entry points detected.\n");
    } else {
        for f in &entry_points {
            out.push_str(&format!("- `{}`\n", f.relative_path));
        }
    }

    out.push_str("\n## Module Structure\n\n");
    let mut modules: Vec<String> = index
        .files
        .iter()
        .filter_map(|f| {
            let parts: Vec<&str> = f.relative_path.splitn(3, '/').collect();
            if parts.len() >= 2 {
                Some(format!("{}/{}", parts[0], parts[1]))
            } else {
                None
            }
        })
        .collect::<std::collections::HashSet<_>>()
        .into_iter()
        .collect();
    modules.sort();

    if modules.is_empty() {
        out.push_str("No module structure detected.\n");
    } else {
        for m in &modules {
            out.push_str(&format!("- `{}/`\n", m));
        }
    }

    out.push_str("\n## Reading Order\n\n");
    out.push_str("Full reading-order onboarding map will be available after Task 16-20.\n");
    out.push_str("In the meantime, explore in this order:\n\n");

    // Simple heuristic: entry points first, then files with most imports.
    let mut files_by_outbound: Vec<_> = index
        .files
        .iter()
        .map(|f| {
            let out_count = index
                .graph
                .edges
                .get(&f.relative_path)
                .map(|v| v.len())
                .unwrap_or(0);
            (out_count, &f.relative_path)
        })
        .collect();
    files_by_outbound.sort_by(|a, b| b.0.cmp(&a.0));

    let top_n = 10.min(files_by_outbound.len());
    for (_, path) in &files_by_outbound[..top_n] {
        out.push_str(&format!("1. `{}`\n", path));
    }

    out
}

fn render_onboarding_json(index: &CodebaseIndex) -> String {
    #[derive(serde::Serialize)]
    struct OnboardingJson<'a> {
        total_files: usize,
        total_tokens: usize,
        languages: Vec<(&'a str, usize)>,
        entry_points: Vec<&'a str>,
        note: &'static str,
    }

    let mut langs: Vec<_> = index
        .language_stats
        .iter()
        .map(|(k, v)| (k.as_str(), v.file_count))
        .collect();
    langs.sort_by(|a, b| b.1.cmp(&a.1));

    let entry_points: Vec<&str> = index
        .files
        .iter()
        .filter(|f| {
            let p = &f.relative_path;
            p == "src/main.rs"
                || p == "src/lib.rs"
                || p == "main.py"
                || p == "index.ts"
                || p == "index.js"
                || p.ends_with("/main.rs")
                || p.ends_with("/lib.rs")
        })
        .map(|f| f.relative_path.as_str())
        .collect();

    let payload = OnboardingJson {
        total_files: index.total_files,
        total_tokens: index.total_tokens,
        languages: langs,
        entry_points,
        note: "Full OnboardingMap available after Task 16-20.",
    };

    serde_json::to_string_pretty(&payload).unwrap_or_default()
}

fn render_onboarding_xml(index: &CodebaseIndex) -> String {
    let mut out = String::from("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<onboarding>\n");
    out.push_str(&format!(
        "  <total_files>{}</total_files>\n",
        index.total_files
    ));
    out.push_str(&format!(
        "  <total_tokens>{}</total_tokens>\n",
        index.total_tokens
    ));
    out.push_str("  <note>Full OnboardingMap available after Task 16-20.</note>\n");
    out.push_str("</onboarding>\n");
    out
}

pub fn run(
    path: &Path,
    _focus: Option<&str>,
    format: &OutputFormat,
    out: Option<&Path>,
) -> Result<(), Box<dyn std::error::Error>> {
    let index = build_index(path)?;
    let content = render_onboarding(&index, format);

    match out {
        Some(out_path) => {
            std::fs::write(out_path, &content)?;
            eprintln!("cxpak: wrote {}", out_path.display());
        }
        None => {
            let stdout = std::io::stdout();
            let mut handle = stdout.lock();
            handle.write_all(content.as_bytes())?;
        }
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::budget::counter::TokenCounter;
    use crate::index::CodebaseIndex;
    use crate::parser::language::{Import, ParseResult, Symbol, SymbolKind, Visibility};
    use crate::scanner::ScannedFile;
    use std::collections::HashMap;
    use std::path::PathBuf;

    fn make_test_index() -> CodebaseIndex {
        let counter = TokenCounter::new();
        let files = vec![
            ScannedFile {
                relative_path: "src/main.rs".to_string(),
                absolute_path: PathBuf::from("/tmp/src/main.rs"),
                language: Some("rust".to_string()),
                size_bytes: 100,
            },
            ScannedFile {
                relative_path: "src/lib.rs".to_string(),
                absolute_path: PathBuf::from("/tmp/src/lib.rs"),
                language: Some("rust".to_string()),
                size_bytes: 200,
            },
            ScannedFile {
                relative_path: "src/commands/mod.rs".to_string(),
                absolute_path: PathBuf::from("/tmp/src/commands/mod.rs"),
                language: Some("rust".to_string()),
                size_bytes: 50,
            },
        ];
        let mut parse_results = HashMap::new();
        parse_results.insert(
            "src/lib.rs".to_string(),
            ParseResult {
                symbols: vec![Symbol {
                    name: "run".to_string(),
                    kind: SymbolKind::Function,
                    visibility: Visibility::Public,
                    signature: "pub fn run()".to_string(),
                    body: "{}".to_string(),
                    start_line: 1,
                    end_line: 1,
                }],
                imports: vec![Import {
                    source: "std".to_string(),
                    names: vec![],
                }],
                exports: vec![],
            },
        );
        let mut content_map = HashMap::new();
        content_map.insert("src/main.rs".to_string(), "fn main() {}".to_string());
        content_map.insert(
            "src/lib.rs".to_string(),
            "use std;\npub fn run() {}".to_string(),
        );
        content_map.insert("src/commands/mod.rs".to_string(), "".to_string());
        CodebaseIndex::build_with_content(files, parse_results, &counter, content_map)
    }

    #[test]
    fn test_render_onboarding_markdown_contains_sections() {
        let index = make_test_index();
        let output = render_onboarding_markdown(&index);
        assert!(output.contains("# Codebase Onboarding Guide"));
        assert!(output.contains("## Overview"));
        assert!(output.contains("## Entry Points"));
        assert!(output.contains("## Module Structure"));
        assert!(output.contains("## Reading Order"));
    }

    #[test]
    fn test_render_onboarding_markdown_lists_entry_points() {
        let index = make_test_index();
        let output = render_onboarding_markdown(&index);
        assert!(output.contains("`src/main.rs`") || output.contains("`src/lib.rs`"));
    }

    #[test]
    fn test_render_onboarding_json_valid() {
        let index = make_test_index();
        let output = render_onboarding_json(&index);
        let parsed: serde_json::Value = serde_json::from_str(&output).expect("valid JSON");
        assert!(parsed["total_files"].as_u64().unwrap() > 0);
        assert!(parsed["note"].as_str().is_some());
    }

    #[test]
    fn test_render_onboarding_xml_contains_tags() {
        let index = make_test_index();
        let output = render_onboarding_xml(&index);
        assert!(output.contains("<onboarding>"));
        assert!(output.contains("<total_files>"));
        assert!(output.contains("</onboarding>"));
    }

    #[test]
    fn test_render_onboarding_dispatches_all_formats() {
        let index = make_test_index();
        let md = render_onboarding(&index, &OutputFormat::Markdown);
        let json = render_onboarding(&index, &OutputFormat::Json);
        let xml = render_onboarding(&index, &OutputFormat::Xml);
        assert!(!md.is_empty());
        assert!(!json.is_empty());
        assert!(!xml.is_empty());
    }

    #[test]
    fn test_render_onboarding_markdown_empty_index() {
        let counter = TokenCounter::new();
        let index =
            CodebaseIndex::build_with_content(vec![], HashMap::new(), &counter, HashMap::new());
        let output = render_onboarding_markdown(&index);
        assert!(output.contains("# Codebase Onboarding Guide"));
        assert!(output.contains("No conventional entry points detected."));
        assert!(output.contains("No module structure detected."));
    }

    #[test]
    fn test_render_onboarding_json_empty_index() {
        let counter = TokenCounter::new();
        let index =
            CodebaseIndex::build_with_content(vec![], HashMap::new(), &counter, HashMap::new());
        let output = render_onboarding_json(&index);
        let parsed: serde_json::Value = serde_json::from_str(&output).expect("valid JSON");
        assert_eq!(parsed["total_files"].as_u64().unwrap(), 0);
    }
}
