pub mod auto_context;
pub mod budget;
pub mod cache;
pub mod cli;
pub mod context_quality;
#[cfg(feature = "daemon")]
pub mod daemon;
#[cfg(feature = "embeddings")]
pub mod embeddings;
pub mod git;
pub mod index;
pub mod intelligence;
pub mod output;
pub mod parser;
pub mod relevance;
pub mod scanner;
pub mod schema;
